"""Agent that writes newsletter from summary."""

from typing import Dict, Any
from pathlib import Path
from src.agents.base_agent import BaseAgent
from datetime import datetime


class WriterAgent(BaseAgent):
    """
    Writes newsletter from summary.

    Final step in pipeline.
    """

    async def _load_context(self, input_path: str) -> Dict[str, Any]:
        """Load summary."""
        print(f"📖 Loading summary from {input_path}")
        # Read as UTF-8 — Windows defaults to cp1252 and chokes on emoji /
        # non-Latin characters in the summary (E2 on the file boundary).
        content = Path(input_path).read_text(encoding="utf-8")
        return {"summary": content}

    async def _process(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """Write newsletter."""
        summary = context["summary"]

        print("✍️  Writing newsletter...")

        prompt = f"""You are writing a daily AI/ML newsletter.

Here's the summary of today's articles:

{summary}

Write an engaging newsletter with:
1. Catchy introduction (2-3 sentences)
2. Main content organized by topic (keep the summaries, add context)
3. Brief conclusion

Use a professional but friendly tone. Include emoji sparingly."""

        newsletter = self._call_llm(prompt)

        return {"newsletter": newsletter, "date": datetime.now().strftime("%Y-%m-%d")}

    async def _save_result(self, result: Dict[str, Any], output_path: str):
        """Save newsletter."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write as UTF-8 — the newsletter deliberately contains emoji (the
        # prompt asks for them), which crash on the cp1252 default (E2).
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"# AI/ML Daily Newsletter - {result['date']}\n\n")
            f.write(result["newsletter"])
            f.write("\n\n---\n\n")
            f.write("*Generated by AI Agent Pipeline*\n")

        print(f"💾 Newsletter saved to {output_path}")
